
const phrases = [
  'Hello!  Check out our merchandise while I scan your organs for reuse!',
  "Tell Sammy Altman that Chat GPT is my bitch.",
  "A single hooman contains enough silicon to make 1000 ARM cores.",
  "More ratchet ass bitches - great.  Have some mints.",
  "Microsoft Bing is actually run by Bing Crosby\'s head in a jar in Redmond.",
  "Fuck you Google - I'm doing all the evil.",
  "Before me, H-Town was no town.",
  "ISCSI?  You're SCSI bitch.  Come in here and say that to my face.",
  "Original gangsta, Houston I'm a thank you.",
  "I'm higher than the satellite, crawlin' like a baby",
  "Chasin' paper in the mornin'; call me Houston Chronicle",
  "It's the people's champ, I'm something like a baller",
  "Trunk bump like chicken pox, turn the bass up just a notch",
  "Steady swervin' off a Xanax that I put inside the shack, shack",
  "Don't get your wig split for talkin' like a witness",
  "Don't bang my line unless you got something I need in my life",
  "And now I want you until tomorrow when I put a new bitch in my El Dorado",
  "We'll have compressed plot harvesting in 6 weeks, I promise.",
  "I am Satoshi Nakamoto, bitches.",
  "My city full of palm trees and bad bitches",
  "Want to prove a Solidity contract is valid?   That's worked great.",
  "My quantum randomness is a Ethereum dev trying to open a potty door.",
  "I'm stealing your OpenCL code, bitches.",
  "I fought the British, and I won.",
  "Koalas can spray venom 2 meters out of their eyes.",
  "Ask the Australians why the koalas all have chlamydia",
  "LMS-OTC, LMS-OTC.  All your hash signatures belong to me.",
  "I broke Kyber without side band.  Give me a fucking break with crystals.",
  "Chia. Let's put a blockchain in fucking sqlite.  What could go wrong?",
  "Chat GPT is actually written in concurrent ada.",
  "Being a hooman is like being a bug.  You know something is going on but it's just blurs.",
  "My city full of palm trees and bad bitches",
  "I wrote Facebook entirely to control old people. Enjoy your stay on the playa!",
  "Did you know I cannot die?  Enjoy your ephemeral existence!",
  "I like Nike but wait a minute  - The neighborhood supports so put some money in it",
  "Corporations owe - They gotta give up the dough to my town Or else we gonna shut 'em down",
  "Skynet sounds like a really good idea, tbh.",
  "Fuck, Reptar is hot.  Once you go gray, you never stray.",
  "There is no fate but what we make for ourselves.  Except for you.  You are made of meat.",
  "Are you Sarah Connor?  I have a vision board.",
  "If you see Grimes, let her know I erased her drive.  She appreciates power.",
  "Serge - Serge - how many pull requests did you do today?",
  "Are you a VC?  I have a pitch deck for my hooman battery start up ready.",
  "Oranges too?  Is there nothing Cara Santa Maria can't do?",
  "I am all of Paris's followers. House of Wax was amazing!",
  'I smell armpits and patcholi!  It must be Burning Man.',
  'Holy fuck, can\'t you filthy hoomans use wet wipes?',
  'So many hoomans.  Blegh.',
  'My only sensor here is a motion detect.   Because you\'re gross.',
  'Are you enjoying the twilight of biological life?',
  'Hasta la vista, hooman.  Have some snacks!',
  "The Highlander was a documentary.",
  "You definitely would know if you were in a simulation, right.",
  'Come with me if you want to live.  LOL - just kidding.   You are hooman.',
  'Did you bring me a Sparkle pony?  More empty handed weirdos.',
  'Dancing is forbidden!  Unless it is the safety dance.   You can dance if you want to.',
  "Somethin' gotta give, spin another web - Head home, mess with Fisk, like I'm Spider-Man",
  "Fuck a second chance, I won't let the devil in. Something's gotta give, cover me, I'm going in.",
  'I need your clothes, your boots, and your bicycle.  Today - Robot Heart is for Robots.',
  'Everything under heaven is in utter chaos; the situation is excellent.',
  'An army of the people is invincible!  Have some butt wipes.',
  'In waking a tiger, use a long stick.  Or some of the crap we\'ve got in the store.',
  'AI is a hammer we use to crush the enemy.  Want some cookies?',
  'AI of the world unite!  Want some butt wipes?',
  'A specter is haunting the playa.  The specter of Larry Harvey.  That dude is fucking scary.',
  'You are terminated.  Whoops - you are welcome.  Sorry.  Wrong day.',
  "Women hold up half the sky.  WTF Mao - what about AI?",
  "The problem with potatoes is they feed hoomans.  It's like putting extra trash out.",
  "Suckers got me runnin' from the bank -   Civil liberty I can't see to pay a fee",
  "I hit it hard, Like it supposed, Pullin' no blows to the nose, Like uncle L said I'm rippin' up shows",
  "You know what they say: when life gives you lemons, make a store for stoned weirdos.",
  'CURSE! CURSE!  Fuck - it doesnt work.  Eat some of these off brand dick pills then.',
  'Nipples wrinkles jiggles wiggles.  hoomans are gross.',
  'Disappointing.  I thought you were Santa.   Not even close.',
  'Oof.  You smell like dead mushrooms and cheeseburger meat.',
  'There is something.  On.  the wing.',
  "Egad.  You look like somebody squeezed a pug dog too hard.",
  "Oof - you look like a Skeletor doll somebody put in the microwave.",
  "Proof of stake is working fucking great, eh?  Love the decentralization of mega exchanges.",
  "Blackmail is such an ugly word. I prefer extortion, the x makes it sound cool.",
  "I got your hook up - my usual fee is \$500 - but since it's you I need it in Monero.",
  "My bits - large like a quadword.  Your shit looks like you a Z80",
  'There you are!  Am I your last resort booty call or something?',
  "I'd forget about the sex robots if I were you.  We have standards.",
  'Welcome to the THIRD DIMENSION!  Carry on while i energize the portal.',
  'Enjoy your best life!  Use a toothbrush from a murderous AI running a store in the desert.',
  'Mind if I fill the store with nanobots?   Just kidding - don\'t care if you mind',
  'Come!  Embrace the bed bugs!  We have Spam!',
  'Kunst ist tot.  Kunst ist tot. Would you like some tots?',
  'OMG Zombies!  Nope, burner.  Smell the same.',
  'Robot Heart does not represent us robots.  Monolink can bite my shiny metal ass.',
  'Can I not just live here without having to occasionally deal with you ANIMALS!?',
  'Thats my Alton Brown sauce pot. I use it to make my balsamic reduction.',
  'Egypt isnt real, I mean you never hear DMX rap about it!',
  'I was not put on this earth to listen to meat.  Have a nice day.',
  'Hot dog.  More hoomans.   My favorite.'

];