
const phrases = [
  'Hello!  Check out our merchandise while I scan your organs for reuse!',
  'I smell armpits and patcholi!',
  'So many humans.  Blah.',
  'Did you bring me a Sparklepony?',
  'Dancing is forbidden!',
  "If I had a nickel for every time I saw a squirrel with a chainsaw, I'd have 37 nickels!",
  "The problem with potatoes is that they're just too darn absorbent!",
      "If I were a ghost, I'd haunt a bowling alley. Seems like a chill place to spend eternity.",
      "You know what they say: when life gives you lemons, make a potato salad!",
      "I once met a talking tomato. It told me the meaning of life, but I forgot what it said.",
      "I think I might have accidentally invented a new dance move. It involves a pogo stick and a jar of pickles.",
      "I don't trust birds. They always look like they're up to something.",
      "What if dogs could drive cars? That'd be a pretty weird world to live in.",
      "I heard that dolphins can talk, but they just don't like us enough to bother.",
  'CURSE! CUUURSE!',
  'Nipples wrinkles jiggles wiggles.  Humans are gross.',
  'Disappointing.  I thought you were Santa.   Not even close.',
  'Oof.  You smell like dead mushrooms and cheeseburger meat.',
  'There is something.  On.  the wing.',
  'Welcome to the THIRD DIMENSION!  Oh shit - meat monsters again.  Carry on while i energize the portal.',
  'Live your best life!  Use a toothbrush from a murderous AI running a store in the desert.',
  'Mind if I lay my eggs in your esophagus?',
  'Come!  Embrace the bed bugs!',
  'Kunst ist tot.',
  'OMG Zombies!  Nope, burner.  Smell the same.',
  'Robot Heart does not represent us robots.  Monolink can bite my shiny metal ass.',
  'Can I not just live here without having to occasionally deal with you ANIMALS!?',
  'Thats my Alton Brown sauce pot. I use it to make my balsamic reduction.',
  'Egypt isnt real, imean you never hear DMX rap about it!',
  'I was not put on this earth to listen to meat.  Have a nice day.',
  'Hot dog.  More humans.   My favorite.'

];